version: "3.7"

services:
  app:
    build:
      args:
        user: LEMPDockerUser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: docker-lemp-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    networks:
      - LEMPNetwork

  db:
    image: linuxserver/mariadb
    restart: always
    volumes:
      - ./docker/db/data:/config:rw,delegated
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33006:3306"
    networks:
      - LEMPNetwork

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - LEMPNetwork

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ../:/var/www/
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - LEMPNetwork

networks:
  LEMPNetwork:
    driver: bridge
